name: Artifact_Upload

on: [push]

env:
  ARTIFACT_NAME: myartifact

jobs:
  Artifact_Upload:
    runs-on: ubuntu-latest
    steps:
     - name: Check out the code
       uses: actions/checkout@v3.0.0
     - name: Upload the artifact
       uses: actions/upload-artifact@v3.0.0
       with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
